services:
  db:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: engbot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  libretranslate:
    image: libretranslate/libretranslate:latest
    restart: always
    ports:
      - "5000:5000"
    environment:
      - LT_DEBUG=false
      - LT_LOAD_ONLY=de,en,ru
    volumes:
      - libretranslate-data:/home/libretranslate/.local
    deploy:
      resources:
        limits:
          memory: 1g

volumes:
  postgres-data:
  libretranslate-data:
